### ISSUE TITLE
resource limits for slave

### ISSUE THREAD

**Issue by alexejmdv** [odavid/jenkins-jnlp-slave#13]
Hi David,

I would like to limit the resources for the slave pods. Tried out several configurations, but could configure limits only for additional containers on the slave pod (helm&maven)

```
clouds:
    aws-eks-kubernetes-cloud:
      type: kubernetes
      namespace: jenkins
      templates:
        - name: jenkins-slave-generic
          image: odavid/jenkins-jnlp-slave:3.35-4-18
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          labels:
            - generic
          remoteFs: /home/jenkins
          jvmArgs: -Xmx2g
          nodeUsageMode: EXCLUSIVE
          privileged: true
          environment:
            DIND: "true"
          yaml: |-
            spec:
              containers:
                - name: maven
                  image: maven:3.6-jdk-8
                  command: ['cat']
                  tty: true
                  resources:
                    requests:
                      cpu: 500m
                      memory: 500Mi
                    limits:
                      cpu: 1000m
                      memory: 1000Mi                  
                - name: helm
                  image: 353316148132.dkr.ecr.eu-central-1.amazonaws.com/ibeo/ci-cd-helper:latest
                  command: ['cat']
                  tty: true
                  resources:
                    requests:
                      cpu: 50m
                      memory: 250Mi
                    limits:
                      cpu: 100m
                      memory: 500Mi
```

Greetings, 
Alexej
